project_id = "ccpejnklrfvgtwryqfrw"

[auth]
enabled = true
site_url = "https://postulpro.com"
additional_redirect_urls = [
  "https://postulpro.com/**",
  "https://www.postulpro.com/**",
  "https://lostykk-postulpro-preview.ignacioo-ch13.workers.dev/**",
  "http://localhost:5173/**",
  "http://localhost:3000/**",
]
jwt_expiry = 3600
enable_refresh_token_rotation = true

[auth.mfa]
max_enrolled_factors = 10

[auth.mfa.totp]
enroll_enabled = true
verify_enabled = true

[auth.mfa.phone]
enroll_enabled = false
verify_enabled = false

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = true
secure_password_change = false
max_frequency = "1m0s"
otp_length = 8
otp_expiry = 3600
