// Shared parse/serialize for the landing-copy tool's structured_json output.
// Moved out of tools.landing-copy.tsx so the same shape can be rendered
// as a visual landing preview both inside a project step and standalone.
//
// The normalizers below are deliberately lenient: a real generation pulled
// from production returned `headlines` as a single string (not an array),
// `features` as `{feature_title, feature_description}` objects (not
// strings), `social_proof` as `{testimonials: [{name, title, quote}]}` (not
// a string), and `faq` items as `{question, answer}` (not `{q, a}`) — the
// model doesn't reliably follow the exact shape asked for in the prompt, so
// every field here accepts its documented shape AND the shapes actually
// observed, instead of silently dropping real content to an empty default.

export type LandingFaq = { q: string; a: string };

export type LandingPageData = {
  headlines: string[];
  subheadline: string;
  hero: string;
  features: string[];
  social_proof: string;
  faq: LandingFaq[];
  cta: string;
  meta_title: string;
  meta_description: string;
  // Never generated by the model — the AI never has a real hero image, so
  // this stays undefined (rendered as an explicit placeholder) until the
  // user deliberately types a real URL in the editor.
  heroImageUrl?: string;
};

function asString(v: unknown): string {
  return typeof v === "string" ? v.trim() : "";
}

function normalizeHeadlines(v: unknown): string[] {
  if (typeof v === "string") return v.trim() ? [v.trim()] : [];
  if (Array.isArray(v)) {
    return v.filter((h): h is string => typeof h === "string" && h.trim().length > 0).slice(0, 5);
  }
  return [];
}

function normalizeFeatures(v: unknown): string[] {
  if (!Array.isArray(v)) return [];
  return v
    .map((f) => {
      if (typeof f === "string") return f.trim();
      if (f && typeof f === "object") {
        const obj = f as Record<string, unknown>;
        const title = asString(obj.feature_title ?? obj.title ?? obj.name ?? obj.heading);
        const desc = asString(obj.feature_description ?? obj.description ?? obj.body ?? obj.text);
        return [title, desc].filter(Boolean).join(": ");
      }
      return "";
    })
    .filter((f) => f.length > 0)
    .slice(0, 8);
}

function normalizeFaq(v: unknown): LandingFaq[] {
  if (!Array.isArray(v)) return [];
  return v
    .map((f): LandingFaq | null => {
      if (!f || typeof f !== "object") return null;
      const obj = f as Record<string, unknown>;
      const q = asString(obj.q ?? obj.question ?? obj.pregunta);
      const a = asString(obj.a ?? obj.answer ?? obj.respuesta);
      if (!q && !a) return null;
      return { q, a };
    })
    .filter((f): f is LandingFaq => f !== null)
    .slice(0, 8);
}

function normalizeSocialProof(v: unknown): string {
  if (typeof v === "string") return v.trim();
  if (v && typeof v === "object") {
    const obj = v as Record<string, unknown>;
    if (Array.isArray(obj.testimonials)) {
      const lines = obj.testimonials
        .map((t) => {
          if (!t || typeof t !== "object") return "";
          const to = t as Record<string, unknown>;
          const quote = asString(to.quote ?? to.text);
          if (!quote) return "";
          const attribution = [asString(to.name), asString(to.title ?? to.role)]
            .filter(Boolean)
            .join(", ");
          return attribution ? `"${quote}" — ${attribution}` : `"${quote}"`;
        })
        .filter((s) => s.length > 0);
      if (lines.length) return lines.join("\n\n");
    }
    // Unknown object shape — best-effort so real copy is never silently
    // dropped just because the model nested it differently than asked.
    const strings = Object.values(obj).filter(
      (x): x is string => typeof x === "string" && x.trim().length > 0,
    );
    if (strings.length) return strings.join("\n\n");
  }
  return "";
}

export function parseLandingJson(raw: string): LandingPageData | null {
  const cleaned = raw
    .replace(/^```json\s*/i, "")
    .replace(/```\s*$/, "")
    .trim();
  const start = cleaned.indexOf("{");
  const end = cleaned.lastIndexOf("}");
  if (start === -1 || end === -1 || end < start) return null;
  try {
    const j = JSON.parse(cleaned.slice(start, end + 1)) as Record<string, unknown>;
    return {
      headlines: normalizeHeadlines(j.headlines),
      subheadline: asString(j.subheadline),
      hero: asString(j.hero),
      features: normalizeFeatures(j.features),
      social_proof: normalizeSocialProof(j.social_proof),
      faq: normalizeFaq(j.faq),
      cta: asString(j.cta),
      meta_title: asString(j.meta_title),
      meta_description: asString(j.meta_description),
      heroImageUrl: asString(j.heroImageUrl) || undefined,
    };
  } catch {
    return null;
  }
}

export function serializeLandingJson(data: LandingPageData): string {
  return JSON.stringify(data, null, 2);
}

export function emptyLandingData(): LandingPageData {
  return {
    headlines: [],
    subheadline: "",
    hero: "",
    features: [],
    social_proof: "",
    faq: [],
    cta: "",
    meta_title: "",
    meta_description: "",
  };
}
