/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LegalRouteImport } from './routes/legal'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RefCodeRouteImport } from './routes/ref.$code'
import { Route as PSlugRouteImport } from './routes/p.$slug'
import { Route as AuthResetPasswordRouteImport } from './routes/auth.reset-password'
import { Route as AuthRegisterRouteImport } from './routes/auth.register'
import { Route as AuthLoginRouteImport } from './routes/auth.login'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as ApiGenerateAiRouteImport } from './routes/api/generate-ai'
import { Route as ApiDeleteAccountRouteImport } from './routes/api/delete-account'
import { Route as ApiCspReportRouteImport } from './routes/api/csp-report'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedMarketplaceRouteImport } from './routes/_authenticated/marketplace'
import { Route as AuthenticatedLibraryRouteImport } from './routes/_authenticated/library'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedBuildRouteImport } from './routes/_authenticated/build'
import { Route as AuthenticatedAffiliatesRouteImport } from './routes/_authenticated/affiliates'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as ApiProjectsIndexRouteImport } from './routes/api/projects/index'
import { Route as AuthenticatedToolsIndexRouteImport } from './routes/_authenticated/tools.index'
import { Route as AuthenticatedProjectsIndexRouteImport } from './routes/_authenticated/projects.index'
import { Route as AuthenticatedMarketplaceIndexRouteImport } from './routes/_authenticated/marketplace.index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as ApiWebhooksHotmartRouteImport } from './routes/api/webhooks/hotmart'
import { Route as ApiProjectsCapabilitiesRouteImport } from './routes/api/projects/capabilities'
import { Route as ApiProjectsIdRouteImport } from './routes/api/projects/$id'
import { Route as ApiNotificationsWelcomeRouteImport } from './routes/api/notifications/welcome'
import { Route as ApiNotificationsWeeklySummaryQaRouteImport } from './routes/api/notifications/weekly-summary-qa'
import { Route as ApiInternalReconcileCreditsRouteImport } from './routes/api/internal/reconcile-credits'
import { Route as ApiBillingWebhookRouteImport } from './routes/api/billing/webhook'
import { Route as ApiBillingPortalRouteImport } from './routes/api/billing/portal'
import { Route as ApiBillingCheckoutRouteImport } from './routes/api/billing/checkout'
import { Route as AuthenticatedToolsSocialPackRouteImport } from './routes/_authenticated/tools.social-pack'
import { Route as AuthenticatedToolsSalesEmailRouteImport } from './routes/_authenticated/tools.sales-email'
import { Route as AuthenticatedToolsLandingCopyRouteImport } from './routes/_authenticated/tools.landing-copy'
import { Route as AuthenticatedToolsEmailSequencesRouteImport } from './routes/_authenticated/tools.email-sequences'
import { Route as AuthenticatedToolsCopywriterRouteImport } from './routes/_authenticated/tools.copywriter'
import { Route as AuthenticatedToolsConsultantRouteImport } from './routes/_authenticated/tools.consultant'
import { Route as AuthenticatedToolsBusinessPlanRouteImport } from './routes/_authenticated/tools.business-plan'
import { Route as AuthenticatedProjectsIdRouteImport } from './routes/_authenticated/projects.$id'
import { Route as AuthenticatedMarketplaceSellRouteImport } from './routes/_authenticated/marketplace.sell'
import { Route as AuthenticatedMarketplaceProductIdRouteImport } from './routes/_authenticated/marketplace.$productId'
import { Route as AuthenticatedAdminPromotionalCreditsRouteImport } from './routes/_authenticated/admin.promotional-credits'
import { Route as ApiProjectsIdRunNextRouteImport } from './routes/api/projects/$id.run-next'
import { Route as ApiProjectsIdResumeRouteImport } from './routes/api/projects/$id.resume'
import { Route as ApiProjectsIdPlanRouteImport } from './routes/api/projects/$id.plan'
import { Route as ApiProjectsIdPauseRouteImport } from './routes/api/projects/$id.pause'
import { Route as ApiProjectsIdConfirmRouteImport } from './routes/api/projects/$id.confirm'
import { Route as ApiProjectsIdBriefRouteImport } from './routes/api/projects/$id.brief'
import { Route as ApiProjectsIdArchiveRouteImport } from './routes/api/projects/$id.archive'
import { Route as ApiProjectsIdStepsStepIdSkipRouteImport } from './routes/api/projects/$id.steps.$stepId.skip'
import { Route as ApiProjectsIdStepsStepIdRunRouteImport } from './routes/api/projects/$id.steps.$stepId.run'
import { Route as ApiProjectsIdStepsStepIdRetryRouteImport } from './routes/api/projects/$id.steps.$stepId.retry'

const LegalRoute = LegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RefCodeRoute = RefCodeRouteImport.update({
  id: '/ref/$code',
  path: '/ref/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const PSlugRoute = PSlugRouteImport.update({
  id: '/p/$slug',
  path: '/p/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/auth/reset-password',
  path: '/auth/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateAiRoute = ApiGenerateAiRouteImport.update({
  id: '/api/generate-ai',
  path: '/api/generate-ai',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDeleteAccountRoute = ApiDeleteAccountRouteImport.update({
  id: '/api/delete-account',
  path: '/api/delete-account',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCspReportRoute = ApiCspReportRouteImport.update({
  id: '/api/csp-report',
  path: '/api/csp-report',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMarketplaceRoute =
  AuthenticatedMarketplaceRouteImport.update({
    id: '/marketplace',
    path: '/marketplace',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLibraryRoute = AuthenticatedLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBuildRoute = AuthenticatedBuildRouteImport.update({
  id: '/build',
  path: '/build',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAffiliatesRoute = AuthenticatedAffiliatesRouteImport.update({
  id: '/affiliates',
  path: '/affiliates',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiProjectsIndexRoute = ApiProjectsIndexRouteImport.update({
  id: '/api/projects/',
  path: '/api/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedToolsIndexRoute = AuthenticatedToolsIndexRouteImport.update({
  id: '/tools/',
  path: '/tools/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProjectsIndexRoute =
  AuthenticatedProjectsIndexRouteImport.update({
    id: '/projects/',
    path: '/projects/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMarketplaceIndexRoute =
  AuthenticatedMarketplaceIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedMarketplaceRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const ApiWebhooksHotmartRoute = ApiWebhooksHotmartRouteImport.update({
  id: '/api/webhooks/hotmart',
  path: '/api/webhooks/hotmart',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProjectsCapabilitiesRoute = ApiProjectsCapabilitiesRouteImport.update({
  id: '/api/projects/capabilities',
  path: '/api/projects/capabilities',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProjectsIdRoute = ApiProjectsIdRouteImport.update({
  id: '/api/projects/$id',
  path: '/api/projects/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNotificationsWelcomeRoute = ApiNotificationsWelcomeRouteImport.update({
  id: '/api/notifications/welcome',
  path: '/api/notifications/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNotificationsWeeklySummaryQaRoute =
  ApiNotificationsWeeklySummaryQaRouteImport.update({
    id: '/api/notifications/weekly-summary-qa',
    path: '/api/notifications/weekly-summary-qa',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiInternalReconcileCreditsRoute =
  ApiInternalReconcileCreditsRouteImport.update({
    id: '/api/internal/reconcile-credits',
    path: '/api/internal/reconcile-credits',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiBillingWebhookRoute = ApiBillingWebhookRouteImport.update({
  id: '/api/billing/webhook',
  path: '/api/billing/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBillingPortalRoute = ApiBillingPortalRouteImport.update({
  id: '/api/billing/portal',
  path: '/api/billing/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBillingCheckoutRoute = ApiBillingCheckoutRouteImport.update({
  id: '/api/billing/checkout',
  path: '/api/billing/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedToolsSocialPackRoute =
  AuthenticatedToolsSocialPackRouteImport.update({
    id: '/tools/social-pack',
    path: '/tools/social-pack',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedToolsSalesEmailRoute =
  AuthenticatedToolsSalesEmailRouteImport.update({
    id: '/tools/sales-email',
    path: '/tools/sales-email',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedToolsLandingCopyRoute =
  AuthenticatedToolsLandingCopyRouteImport.update({
    id: '/tools/landing-copy',
    path: '/tools/landing-copy',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedToolsEmailSequencesRoute =
  AuthenticatedToolsEmailSequencesRouteImport.update({
    id: '/tools/email-sequences',
    path: '/tools/email-sequences',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedToolsCopywriterRoute =
  AuthenticatedToolsCopywriterRouteImport.update({
    id: '/tools/copywriter',
    path: '/tools/copywriter',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedToolsConsultantRoute =
  AuthenticatedToolsConsultantRouteImport.update({
    id: '/tools/consultant',
    path: '/tools/consultant',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedToolsBusinessPlanRoute =
  AuthenticatedToolsBusinessPlanRouteImport.update({
    id: '/tools/business-plan',
    path: '/tools/business-plan',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProjectsIdRoute = AuthenticatedProjectsIdRouteImport.update({
  id: '/projects/$id',
  path: '/projects/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMarketplaceSellRoute =
  AuthenticatedMarketplaceSellRouteImport.update({
    id: '/sell',
    path: '/sell',
    getParentRoute: () => AuthenticatedMarketplaceRoute,
  } as any)
const AuthenticatedMarketplaceProductIdRoute =
  AuthenticatedMarketplaceProductIdRouteImport.update({
    id: '/$productId',
    path: '/$productId',
    getParentRoute: () => AuthenticatedMarketplaceRoute,
  } as any)
const AuthenticatedAdminPromotionalCreditsRoute =
  AuthenticatedAdminPromotionalCreditsRouteImport.update({
    id: '/promotional-credits',
    path: '/promotional-credits',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const ApiProjectsIdRunNextRoute = ApiProjectsIdRunNextRouteImport.update({
  id: '/run-next',
  path: '/run-next',
  getParentRoute: () => ApiProjectsIdRoute,
} as any)
const ApiProjectsIdResumeRoute = ApiProjectsIdResumeRouteImport.update({
  id: '/resume',
  path: '/resume',
  getParentRoute: () => ApiProjectsIdRoute,
} as any)
const ApiProjectsIdPlanRoute = ApiProjectsIdPlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => ApiProjectsIdRoute,
} as any)
const ApiProjectsIdPauseRoute = ApiProjectsIdPauseRouteImport.update({
  id: '/pause',
  path: '/pause',
  getParentRoute: () => ApiProjectsIdRoute,
} as any)
const ApiProjectsIdConfirmRoute = ApiProjectsIdConfirmRouteImport.update({
  id: '/confirm',
  path: '/confirm',
  getParentRoute: () => ApiProjectsIdRoute,
} as any)
const ApiProjectsIdBriefRoute = ApiProjectsIdBriefRouteImport.update({
  id: '/brief',
  path: '/brief',
  getParentRoute: () => ApiProjectsIdRoute,
} as any)
const ApiProjectsIdArchiveRoute = ApiProjectsIdArchiveRouteImport.update({
  id: '/archive',
  path: '/archive',
  getParentRoute: () => ApiProjectsIdRoute,
} as any)
const ApiProjectsIdStepsStepIdSkipRoute =
  ApiProjectsIdStepsStepIdSkipRouteImport.update({
    id: '/steps/$stepId/skip',
    path: '/steps/$stepId/skip',
    getParentRoute: () => ApiProjectsIdRoute,
  } as any)
const ApiProjectsIdStepsStepIdRunRoute =
  ApiProjectsIdStepsStepIdRunRouteImport.update({
    id: '/steps/$stepId/run',
    path: '/steps/$stepId/run',
    getParentRoute: () => ApiProjectsIdRoute,
  } as any)
const ApiProjectsIdStepsStepIdRetryRoute =
  ApiProjectsIdStepsStepIdRetryRouteImport.update({
    id: '/steps/$stepId/retry',
    path: '/steps/$stepId/retry',
    getParentRoute: () => ApiProjectsIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/demo': typeof DemoRoute
  '/legal': typeof LegalRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/affiliates': typeof AuthenticatedAffiliatesRoute
  '/build': typeof AuthenticatedBuildRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/library': typeof AuthenticatedLibraryRoute
  '/marketplace': typeof AuthenticatedMarketplaceRouteWithChildren
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/api/csp-report': typeof ApiCspReportRoute
  '/api/delete-account': typeof ApiDeleteAccountRoute
  '/api/generate-ai': typeof ApiGenerateAiRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/p/$slug': typeof PSlugRoute
  '/ref/$code': typeof RefCodeRoute
  '/admin/promotional-credits': typeof AuthenticatedAdminPromotionalCreditsRoute
  '/marketplace/$productId': typeof AuthenticatedMarketplaceProductIdRoute
  '/marketplace/sell': typeof AuthenticatedMarketplaceSellRoute
  '/projects/$id': typeof AuthenticatedProjectsIdRoute
  '/tools/business-plan': typeof AuthenticatedToolsBusinessPlanRoute
  '/tools/consultant': typeof AuthenticatedToolsConsultantRoute
  '/tools/copywriter': typeof AuthenticatedToolsCopywriterRoute
  '/tools/email-sequences': typeof AuthenticatedToolsEmailSequencesRoute
  '/tools/landing-copy': typeof AuthenticatedToolsLandingCopyRoute
  '/tools/sales-email': typeof AuthenticatedToolsSalesEmailRoute
  '/tools/social-pack': typeof AuthenticatedToolsSocialPackRoute
  '/api/billing/checkout': typeof ApiBillingCheckoutRoute
  '/api/billing/portal': typeof ApiBillingPortalRoute
  '/api/billing/webhook': typeof ApiBillingWebhookRoute
  '/api/internal/reconcile-credits': typeof ApiInternalReconcileCreditsRoute
  '/api/notifications/weekly-summary-qa': typeof ApiNotificationsWeeklySummaryQaRoute
  '/api/notifications/welcome': typeof ApiNotificationsWelcomeRoute
  '/api/projects/$id': typeof ApiProjectsIdRouteWithChildren
  '/api/projects/capabilities': typeof ApiProjectsCapabilitiesRoute
  '/api/webhooks/hotmart': typeof ApiWebhooksHotmartRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/marketplace/': typeof AuthenticatedMarketplaceIndexRoute
  '/projects/': typeof AuthenticatedProjectsIndexRoute
  '/tools/': typeof AuthenticatedToolsIndexRoute
  '/api/projects/': typeof ApiProjectsIndexRoute
  '/api/projects/$id/archive': typeof ApiProjectsIdArchiveRoute
  '/api/projects/$id/brief': typeof ApiProjectsIdBriefRoute
  '/api/projects/$id/confirm': typeof ApiProjectsIdConfirmRoute
  '/api/projects/$id/pause': typeof ApiProjectsIdPauseRoute
  '/api/projects/$id/plan': typeof ApiProjectsIdPlanRoute
  '/api/projects/$id/resume': typeof ApiProjectsIdResumeRoute
  '/api/projects/$id/run-next': typeof ApiProjectsIdRunNextRoute
  '/api/projects/$id/steps/$stepId/retry': typeof ApiProjectsIdStepsStepIdRetryRoute
  '/api/projects/$id/steps/$stepId/run': typeof ApiProjectsIdStepsStepIdRunRoute
  '/api/projects/$id/steps/$stepId/skip': typeof ApiProjectsIdStepsStepIdSkipRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/demo': typeof DemoRoute
  '/legal': typeof LegalRoute
  '/affiliates': typeof AuthenticatedAffiliatesRoute
  '/build': typeof AuthenticatedBuildRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/library': typeof AuthenticatedLibraryRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/api/csp-report': typeof ApiCspReportRoute
  '/api/delete-account': typeof ApiDeleteAccountRoute
  '/api/generate-ai': typeof ApiGenerateAiRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/p/$slug': typeof PSlugRoute
  '/ref/$code': typeof RefCodeRoute
  '/admin/promotional-credits': typeof AuthenticatedAdminPromotionalCreditsRoute
  '/marketplace/$productId': typeof AuthenticatedMarketplaceProductIdRoute
  '/marketplace/sell': typeof AuthenticatedMarketplaceSellRoute
  '/projects/$id': typeof AuthenticatedProjectsIdRoute
  '/tools/business-plan': typeof AuthenticatedToolsBusinessPlanRoute
  '/tools/consultant': typeof AuthenticatedToolsConsultantRoute
  '/tools/copywriter': typeof AuthenticatedToolsCopywriterRoute
  '/tools/email-sequences': typeof AuthenticatedToolsEmailSequencesRoute
  '/tools/landing-copy': typeof AuthenticatedToolsLandingCopyRoute
  '/tools/sales-email': typeof AuthenticatedToolsSalesEmailRoute
  '/tools/social-pack': typeof AuthenticatedToolsSocialPackRoute
  '/api/billing/checkout': typeof ApiBillingCheckoutRoute
  '/api/billing/portal': typeof ApiBillingPortalRoute
  '/api/billing/webhook': typeof ApiBillingWebhookRoute
  '/api/internal/reconcile-credits': typeof ApiInternalReconcileCreditsRoute
  '/api/notifications/weekly-summary-qa': typeof ApiNotificationsWeeklySummaryQaRoute
  '/api/notifications/welcome': typeof ApiNotificationsWelcomeRoute
  '/api/projects/$id': typeof ApiProjectsIdRouteWithChildren
  '/api/projects/capabilities': typeof ApiProjectsCapabilitiesRoute
  '/api/webhooks/hotmart': typeof ApiWebhooksHotmartRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/marketplace': typeof AuthenticatedMarketplaceIndexRoute
  '/projects': typeof AuthenticatedProjectsIndexRoute
  '/tools': typeof AuthenticatedToolsIndexRoute
  '/api/projects': typeof ApiProjectsIndexRoute
  '/api/projects/$id/archive': typeof ApiProjectsIdArchiveRoute
  '/api/projects/$id/brief': typeof ApiProjectsIdBriefRoute
  '/api/projects/$id/confirm': typeof ApiProjectsIdConfirmRoute
  '/api/projects/$id/pause': typeof ApiProjectsIdPauseRoute
  '/api/projects/$id/plan': typeof ApiProjectsIdPlanRoute
  '/api/projects/$id/resume': typeof ApiProjectsIdResumeRoute
  '/api/projects/$id/run-next': typeof ApiProjectsIdRunNextRoute
  '/api/projects/$id/steps/$stepId/retry': typeof ApiProjectsIdStepsStepIdRetryRoute
  '/api/projects/$id/steps/$stepId/run': typeof ApiProjectsIdStepsStepIdRunRoute
  '/api/projects/$id/steps/$stepId/skip': typeof ApiProjectsIdStepsStepIdSkipRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/demo': typeof DemoRoute
  '/legal': typeof LegalRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/affiliates': typeof AuthenticatedAffiliatesRoute
  '/_authenticated/build': typeof AuthenticatedBuildRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/library': typeof AuthenticatedLibraryRoute
  '/_authenticated/marketplace': typeof AuthenticatedMarketplaceRouteWithChildren
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/api/csp-report': typeof ApiCspReportRoute
  '/api/delete-account': typeof ApiDeleteAccountRoute
  '/api/generate-ai': typeof ApiGenerateAiRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/p/$slug': typeof PSlugRoute
  '/ref/$code': typeof RefCodeRoute
  '/_authenticated/admin/promotional-credits': typeof AuthenticatedAdminPromotionalCreditsRoute
  '/_authenticated/marketplace/$productId': typeof AuthenticatedMarketplaceProductIdRoute
  '/_authenticated/marketplace/sell': typeof AuthenticatedMarketplaceSellRoute
  '/_authenticated/projects/$id': typeof AuthenticatedProjectsIdRoute
  '/_authenticated/tools/business-plan': typeof AuthenticatedToolsBusinessPlanRoute
  '/_authenticated/tools/consultant': typeof AuthenticatedToolsConsultantRoute
  '/_authenticated/tools/copywriter': typeof AuthenticatedToolsCopywriterRoute
  '/_authenticated/tools/email-sequences': typeof AuthenticatedToolsEmailSequencesRoute
  '/_authenticated/tools/landing-copy': typeof AuthenticatedToolsLandingCopyRoute
  '/_authenticated/tools/sales-email': typeof AuthenticatedToolsSalesEmailRoute
  '/_authenticated/tools/social-pack': typeof AuthenticatedToolsSocialPackRoute
  '/api/billing/checkout': typeof ApiBillingCheckoutRoute
  '/api/billing/portal': typeof ApiBillingPortalRoute
  '/api/billing/webhook': typeof ApiBillingWebhookRoute
  '/api/internal/reconcile-credits': typeof ApiInternalReconcileCreditsRoute
  '/api/notifications/weekly-summary-qa': typeof ApiNotificationsWeeklySummaryQaRoute
  '/api/notifications/welcome': typeof ApiNotificationsWelcomeRoute
  '/api/projects/$id': typeof ApiProjectsIdRouteWithChildren
  '/api/projects/capabilities': typeof ApiProjectsCapabilitiesRoute
  '/api/webhooks/hotmart': typeof ApiWebhooksHotmartRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/marketplace/': typeof AuthenticatedMarketplaceIndexRoute
  '/_authenticated/projects/': typeof AuthenticatedProjectsIndexRoute
  '/_authenticated/tools/': typeof AuthenticatedToolsIndexRoute
  '/api/projects/': typeof ApiProjectsIndexRoute
  '/api/projects/$id/archive': typeof ApiProjectsIdArchiveRoute
  '/api/projects/$id/brief': typeof ApiProjectsIdBriefRoute
  '/api/projects/$id/confirm': typeof ApiProjectsIdConfirmRoute
  '/api/projects/$id/pause': typeof ApiProjectsIdPauseRoute
  '/api/projects/$id/plan': typeof ApiProjectsIdPlanRoute
  '/api/projects/$id/resume': typeof ApiProjectsIdResumeRoute
  '/api/projects/$id/run-next': typeof ApiProjectsIdRunNextRoute
  '/api/projects/$id/steps/$stepId/retry': typeof ApiProjectsIdStepsStepIdRetryRoute
  '/api/projects/$id/steps/$stepId/run': typeof ApiProjectsIdStepsStepIdRunRoute
  '/api/projects/$id/steps/$stepId/skip': typeof ApiProjectsIdStepsStepIdSkipRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/demo'
    | '/legal'
    | '/admin'
    | '/affiliates'
    | '/build'
    | '/dashboard'
    | '/library'
    | '/marketplace'
    | '/onboarding'
    | '/settings'
    | '/api/csp-report'
    | '/api/delete-account'
    | '/api/generate-ai'
    | '/auth/callback'
    | '/auth/login'
    | '/auth/register'
    | '/auth/reset-password'
    | '/p/$slug'
    | '/ref/$code'
    | '/admin/promotional-credits'
    | '/marketplace/$productId'
    | '/marketplace/sell'
    | '/projects/$id'
    | '/tools/business-plan'
    | '/tools/consultant'
    | '/tools/copywriter'
    | '/tools/email-sequences'
    | '/tools/landing-copy'
    | '/tools/sales-email'
    | '/tools/social-pack'
    | '/api/billing/checkout'
    | '/api/billing/portal'
    | '/api/billing/webhook'
    | '/api/internal/reconcile-credits'
    | '/api/notifications/weekly-summary-qa'
    | '/api/notifications/welcome'
    | '/api/projects/$id'
    | '/api/projects/capabilities'
    | '/api/webhooks/hotmart'
    | '/admin/'
    | '/marketplace/'
    | '/projects/'
    | '/tools/'
    | '/api/projects/'
    | '/api/projects/$id/archive'
    | '/api/projects/$id/brief'
    | '/api/projects/$id/confirm'
    | '/api/projects/$id/pause'
    | '/api/projects/$id/plan'
    | '/api/projects/$id/resume'
    | '/api/projects/$id/run-next'
    | '/api/projects/$id/steps/$stepId/retry'
    | '/api/projects/$id/steps/$stepId/run'
    | '/api/projects/$id/steps/$stepId/skip'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/demo'
    | '/legal'
    | '/affiliates'
    | '/build'
    | '/dashboard'
    | '/library'
    | '/onboarding'
    | '/settings'
    | '/api/csp-report'
    | '/api/delete-account'
    | '/api/generate-ai'
    | '/auth/callback'
    | '/auth/login'
    | '/auth/register'
    | '/auth/reset-password'
    | '/p/$slug'
    | '/ref/$code'
    | '/admin/promotional-credits'
    | '/marketplace/$productId'
    | '/marketplace/sell'
    | '/projects/$id'
    | '/tools/business-plan'
    | '/tools/consultant'
    | '/tools/copywriter'
    | '/tools/email-sequences'
    | '/tools/landing-copy'
    | '/tools/sales-email'
    | '/tools/social-pack'
    | '/api/billing/checkout'
    | '/api/billing/portal'
    | '/api/billing/webhook'
    | '/api/internal/reconcile-credits'
    | '/api/notifications/weekly-summary-qa'
    | '/api/notifications/welcome'
    | '/api/projects/$id'
    | '/api/projects/capabilities'
    | '/api/webhooks/hotmart'
    | '/admin'
    | '/marketplace'
    | '/projects'
    | '/tools'
    | '/api/projects'
    | '/api/projects/$id/archive'
    | '/api/projects/$id/brief'
    | '/api/projects/$id/confirm'
    | '/api/projects/$id/pause'
    | '/api/projects/$id/plan'
    | '/api/projects/$id/resume'
    | '/api/projects/$id/run-next'
    | '/api/projects/$id/steps/$stepId/retry'
    | '/api/projects/$id/steps/$stepId/run'
    | '/api/projects/$id/steps/$stepId/skip'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/demo'
    | '/legal'
    | '/_authenticated/admin'
    | '/_authenticated/affiliates'
    | '/_authenticated/build'
    | '/_authenticated/dashboard'
    | '/_authenticated/library'
    | '/_authenticated/marketplace'
    | '/_authenticated/onboarding'
    | '/_authenticated/settings'
    | '/api/csp-report'
    | '/api/delete-account'
    | '/api/generate-ai'
    | '/auth/callback'
    | '/auth/login'
    | '/auth/register'
    | '/auth/reset-password'
    | '/p/$slug'
    | '/ref/$code'
    | '/_authenticated/admin/promotional-credits'
    | '/_authenticated/marketplace/$productId'
    | '/_authenticated/marketplace/sell'
    | '/_authenticated/projects/$id'
    | '/_authenticated/tools/business-plan'
    | '/_authenticated/tools/consultant'
    | '/_authenticated/tools/copywriter'
    | '/_authenticated/tools/email-sequences'
    | '/_authenticated/tools/landing-copy'
    | '/_authenticated/tools/sales-email'
    | '/_authenticated/tools/social-pack'
    | '/api/billing/checkout'
    | '/api/billing/portal'
    | '/api/billing/webhook'
    | '/api/internal/reconcile-credits'
    | '/api/notifications/weekly-summary-qa'
    | '/api/notifications/welcome'
    | '/api/projects/$id'
    | '/api/projects/capabilities'
    | '/api/webhooks/hotmart'
    | '/_authenticated/admin/'
    | '/_authenticated/marketplace/'
    | '/_authenticated/projects/'
    | '/_authenticated/tools/'
    | '/api/projects/'
    | '/api/projects/$id/archive'
    | '/api/projects/$id/brief'
    | '/api/projects/$id/confirm'
    | '/api/projects/$id/pause'
    | '/api/projects/$id/plan'
    | '/api/projects/$id/resume'
    | '/api/projects/$id/run-next'
    | '/api/projects/$id/steps/$stepId/retry'
    | '/api/projects/$id/steps/$stepId/run'
    | '/api/projects/$id/steps/$stepId/skip'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  DemoRoute: typeof DemoRoute
  LegalRoute: typeof LegalRoute
  ApiCspReportRoute: typeof ApiCspReportRoute
  ApiDeleteAccountRoute: typeof ApiDeleteAccountRoute
  ApiGenerateAiRoute: typeof ApiGenerateAiRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  PSlugRoute: typeof PSlugRoute
  RefCodeRoute: typeof RefCodeRoute
  ApiBillingCheckoutRoute: typeof ApiBillingCheckoutRoute
  ApiBillingPortalRoute: typeof ApiBillingPortalRoute
  ApiBillingWebhookRoute: typeof ApiBillingWebhookRoute
  ApiInternalReconcileCreditsRoute: typeof ApiInternalReconcileCreditsRoute
  ApiNotificationsWeeklySummaryQaRoute: typeof ApiNotificationsWeeklySummaryQaRoute
  ApiNotificationsWelcomeRoute: typeof ApiNotificationsWelcomeRoute
  ApiProjectsIdRoute: typeof ApiProjectsIdRouteWithChildren
  ApiProjectsCapabilitiesRoute: typeof ApiProjectsCapabilitiesRoute
  ApiWebhooksHotmartRoute: typeof ApiWebhooksHotmartRoute
  ApiProjectsIndexRoute: typeof ApiProjectsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/legal': {
      id: '/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof LegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ref/$code': {
      id: '/ref/$code'
      path: '/ref/$code'
      fullPath: '/ref/$code'
      preLoaderRoute: typeof RefCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$slug': {
      id: '/p/$slug'
      path: '/p/$slug'
      fullPath: '/p/$slug'
      preLoaderRoute: typeof PSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/auth/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate-ai': {
      id: '/api/generate-ai'
      path: '/api/generate-ai'
      fullPath: '/api/generate-ai'
      preLoaderRoute: typeof ApiGenerateAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/delete-account': {
      id: '/api/delete-account'
      path: '/api/delete-account'
      fullPath: '/api/delete-account'
      preLoaderRoute: typeof ApiDeleteAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/csp-report': {
      id: '/api/csp-report'
      path: '/api/csp-report'
      fullPath: '/api/csp-report'
      preLoaderRoute: typeof ApiCspReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/marketplace': {
      id: '/_authenticated/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof AuthenticatedMarketplaceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/library': {
      id: '/_authenticated/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof AuthenticatedLibraryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/build': {
      id: '/_authenticated/build'
      path: '/build'
      fullPath: '/build'
      preLoaderRoute: typeof AuthenticatedBuildRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/affiliates': {
      id: '/_authenticated/affiliates'
      path: '/affiliates'
      fullPath: '/affiliates'
      preLoaderRoute: typeof AuthenticatedAffiliatesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/projects/': {
      id: '/api/projects/'
      path: '/api/projects'
      fullPath: '/api/projects/'
      preLoaderRoute: typeof ApiProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/tools/': {
      id: '/_authenticated/tools/'
      path: '/tools'
      fullPath: '/tools/'
      preLoaderRoute: typeof AuthenticatedToolsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projects/': {
      id: '/_authenticated/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof AuthenticatedProjectsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/marketplace/': {
      id: '/_authenticated/marketplace/'
      path: '/'
      fullPath: '/marketplace/'
      preLoaderRoute: typeof AuthenticatedMarketplaceIndexRouteImport
      parentRoute: typeof AuthenticatedMarketplaceRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/api/webhooks/hotmart': {
      id: '/api/webhooks/hotmart'
      path: '/api/webhooks/hotmart'
      fullPath: '/api/webhooks/hotmart'
      preLoaderRoute: typeof ApiWebhooksHotmartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/projects/capabilities': {
      id: '/api/projects/capabilities'
      path: '/api/projects/capabilities'
      fullPath: '/api/projects/capabilities'
      preLoaderRoute: typeof ApiProjectsCapabilitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/projects/$id': {
      id: '/api/projects/$id'
      path: '/api/projects/$id'
      fullPath: '/api/projects/$id'
      preLoaderRoute: typeof ApiProjectsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/notifications/welcome': {
      id: '/api/notifications/welcome'
      path: '/api/notifications/welcome'
      fullPath: '/api/notifications/welcome'
      preLoaderRoute: typeof ApiNotificationsWelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/notifications/weekly-summary-qa': {
      id: '/api/notifications/weekly-summary-qa'
      path: '/api/notifications/weekly-summary-qa'
      fullPath: '/api/notifications/weekly-summary-qa'
      preLoaderRoute: typeof ApiNotificationsWeeklySummaryQaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/internal/reconcile-credits': {
      id: '/api/internal/reconcile-credits'
      path: '/api/internal/reconcile-credits'
      fullPath: '/api/internal/reconcile-credits'
      preLoaderRoute: typeof ApiInternalReconcileCreditsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/billing/webhook': {
      id: '/api/billing/webhook'
      path: '/api/billing/webhook'
      fullPath: '/api/billing/webhook'
      preLoaderRoute: typeof ApiBillingWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/billing/portal': {
      id: '/api/billing/portal'
      path: '/api/billing/portal'
      fullPath: '/api/billing/portal'
      preLoaderRoute: typeof ApiBillingPortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/billing/checkout': {
      id: '/api/billing/checkout'
      path: '/api/billing/checkout'
      fullPath: '/api/billing/checkout'
      preLoaderRoute: typeof ApiBillingCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/tools/social-pack': {
      id: '/_authenticated/tools/social-pack'
      path: '/tools/social-pack'
      fullPath: '/tools/social-pack'
      preLoaderRoute: typeof AuthenticatedToolsSocialPackRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tools/sales-email': {
      id: '/_authenticated/tools/sales-email'
      path: '/tools/sales-email'
      fullPath: '/tools/sales-email'
      preLoaderRoute: typeof AuthenticatedToolsSalesEmailRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tools/landing-copy': {
      id: '/_authenticated/tools/landing-copy'
      path: '/tools/landing-copy'
      fullPath: '/tools/landing-copy'
      preLoaderRoute: typeof AuthenticatedToolsLandingCopyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tools/email-sequences': {
      id: '/_authenticated/tools/email-sequences'
      path: '/tools/email-sequences'
      fullPath: '/tools/email-sequences'
      preLoaderRoute: typeof AuthenticatedToolsEmailSequencesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tools/copywriter': {
      id: '/_authenticated/tools/copywriter'
      path: '/tools/copywriter'
      fullPath: '/tools/copywriter'
      preLoaderRoute: typeof AuthenticatedToolsCopywriterRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tools/consultant': {
      id: '/_authenticated/tools/consultant'
      path: '/tools/consultant'
      fullPath: '/tools/consultant'
      preLoaderRoute: typeof AuthenticatedToolsConsultantRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tools/business-plan': {
      id: '/_authenticated/tools/business-plan'
      path: '/tools/business-plan'
      fullPath: '/tools/business-plan'
      preLoaderRoute: typeof AuthenticatedToolsBusinessPlanRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projects/$id': {
      id: '/_authenticated/projects/$id'
      path: '/projects/$id'
      fullPath: '/projects/$id'
      preLoaderRoute: typeof AuthenticatedProjectsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/marketplace/sell': {
      id: '/_authenticated/marketplace/sell'
      path: '/sell'
      fullPath: '/marketplace/sell'
      preLoaderRoute: typeof AuthenticatedMarketplaceSellRouteImport
      parentRoute: typeof AuthenticatedMarketplaceRoute
    }
    '/_authenticated/marketplace/$productId': {
      id: '/_authenticated/marketplace/$productId'
      path: '/$productId'
      fullPath: '/marketplace/$productId'
      preLoaderRoute: typeof AuthenticatedMarketplaceProductIdRouteImport
      parentRoute: typeof AuthenticatedMarketplaceRoute
    }
    '/_authenticated/admin/promotional-credits': {
      id: '/_authenticated/admin/promotional-credits'
      path: '/promotional-credits'
      fullPath: '/admin/promotional-credits'
      preLoaderRoute: typeof AuthenticatedAdminPromotionalCreditsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/api/projects/$id/run-next': {
      id: '/api/projects/$id/run-next'
      path: '/run-next'
      fullPath: '/api/projects/$id/run-next'
      preLoaderRoute: typeof ApiProjectsIdRunNextRouteImport
      parentRoute: typeof ApiProjectsIdRoute
    }
    '/api/projects/$id/resume': {
      id: '/api/projects/$id/resume'
      path: '/resume'
      fullPath: '/api/projects/$id/resume'
      preLoaderRoute: typeof ApiProjectsIdResumeRouteImport
      parentRoute: typeof ApiProjectsIdRoute
    }
    '/api/projects/$id/plan': {
      id: '/api/projects/$id/plan'
      path: '/plan'
      fullPath: '/api/projects/$id/plan'
      preLoaderRoute: typeof ApiProjectsIdPlanRouteImport
      parentRoute: typeof ApiProjectsIdRoute
    }
    '/api/projects/$id/pause': {
      id: '/api/projects/$id/pause'
      path: '/pause'
      fullPath: '/api/projects/$id/pause'
      preLoaderRoute: typeof ApiProjectsIdPauseRouteImport
      parentRoute: typeof ApiProjectsIdRoute
    }
    '/api/projects/$id/confirm': {
      id: '/api/projects/$id/confirm'
      path: '/confirm'
      fullPath: '/api/projects/$id/confirm'
      preLoaderRoute: typeof ApiProjectsIdConfirmRouteImport
      parentRoute: typeof ApiProjectsIdRoute
    }
    '/api/projects/$id/brief': {
      id: '/api/projects/$id/brief'
      path: '/brief'
      fullPath: '/api/projects/$id/brief'
      preLoaderRoute: typeof ApiProjectsIdBriefRouteImport
      parentRoute: typeof ApiProjectsIdRoute
    }
    '/api/projects/$id/archive': {
      id: '/api/projects/$id/archive'
      path: '/archive'
      fullPath: '/api/projects/$id/archive'
      preLoaderRoute: typeof ApiProjectsIdArchiveRouteImport
      parentRoute: typeof ApiProjectsIdRoute
    }
    '/api/projects/$id/steps/$stepId/skip': {
      id: '/api/projects/$id/steps/$stepId/skip'
      path: '/steps/$stepId/skip'
      fullPath: '/api/projects/$id/steps/$stepId/skip'
      preLoaderRoute: typeof ApiProjectsIdStepsStepIdSkipRouteImport
      parentRoute: typeof ApiProjectsIdRoute
    }
    '/api/projects/$id/steps/$stepId/run': {
      id: '/api/projects/$id/steps/$stepId/run'
      path: '/steps/$stepId/run'
      fullPath: '/api/projects/$id/steps/$stepId/run'
      preLoaderRoute: typeof ApiProjectsIdStepsStepIdRunRouteImport
      parentRoute: typeof ApiProjectsIdRoute
    }
    '/api/projects/$id/steps/$stepId/retry': {
      id: '/api/projects/$id/steps/$stepId/retry'
      path: '/steps/$stepId/retry'
      fullPath: '/api/projects/$id/steps/$stepId/retry'
      preLoaderRoute: typeof ApiProjectsIdStepsStepIdRetryRouteImport
      parentRoute: typeof ApiProjectsIdRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminPromotionalCreditsRoute: typeof AuthenticatedAdminPromotionalCreditsRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminPromotionalCreditsRoute:
    AuthenticatedAdminPromotionalCreditsRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedMarketplaceRouteChildren {
  AuthenticatedMarketplaceProductIdRoute: typeof AuthenticatedMarketplaceProductIdRoute
  AuthenticatedMarketplaceSellRoute: typeof AuthenticatedMarketplaceSellRoute
  AuthenticatedMarketplaceIndexRoute: typeof AuthenticatedMarketplaceIndexRoute
}

const AuthenticatedMarketplaceRouteChildren: AuthenticatedMarketplaceRouteChildren =
  {
    AuthenticatedMarketplaceProductIdRoute:
      AuthenticatedMarketplaceProductIdRoute,
    AuthenticatedMarketplaceSellRoute: AuthenticatedMarketplaceSellRoute,
    AuthenticatedMarketplaceIndexRoute: AuthenticatedMarketplaceIndexRoute,
  }

const AuthenticatedMarketplaceRouteWithChildren =
  AuthenticatedMarketplaceRoute._addFileChildren(
    AuthenticatedMarketplaceRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedAffiliatesRoute: typeof AuthenticatedAffiliatesRoute
  AuthenticatedBuildRoute: typeof AuthenticatedBuildRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedLibraryRoute: typeof AuthenticatedLibraryRoute
  AuthenticatedMarketplaceRoute: typeof AuthenticatedMarketplaceRouteWithChildren
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedProjectsIdRoute: typeof AuthenticatedProjectsIdRoute
  AuthenticatedToolsBusinessPlanRoute: typeof AuthenticatedToolsBusinessPlanRoute
  AuthenticatedToolsConsultantRoute: typeof AuthenticatedToolsConsultantRoute
  AuthenticatedToolsCopywriterRoute: typeof AuthenticatedToolsCopywriterRoute
  AuthenticatedToolsEmailSequencesRoute: typeof AuthenticatedToolsEmailSequencesRoute
  AuthenticatedToolsLandingCopyRoute: typeof AuthenticatedToolsLandingCopyRoute
  AuthenticatedToolsSalesEmailRoute: typeof AuthenticatedToolsSalesEmailRoute
  AuthenticatedToolsSocialPackRoute: typeof AuthenticatedToolsSocialPackRoute
  AuthenticatedProjectsIndexRoute: typeof AuthenticatedProjectsIndexRoute
  AuthenticatedToolsIndexRoute: typeof AuthenticatedToolsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedAffiliatesRoute: AuthenticatedAffiliatesRoute,
  AuthenticatedBuildRoute: AuthenticatedBuildRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedLibraryRoute: AuthenticatedLibraryRoute,
  AuthenticatedMarketplaceRoute: AuthenticatedMarketplaceRouteWithChildren,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedProjectsIdRoute: AuthenticatedProjectsIdRoute,
  AuthenticatedToolsBusinessPlanRoute: AuthenticatedToolsBusinessPlanRoute,
  AuthenticatedToolsConsultantRoute: AuthenticatedToolsConsultantRoute,
  AuthenticatedToolsCopywriterRoute: AuthenticatedToolsCopywriterRoute,
  AuthenticatedToolsEmailSequencesRoute: AuthenticatedToolsEmailSequencesRoute,
  AuthenticatedToolsLandingCopyRoute: AuthenticatedToolsLandingCopyRoute,
  AuthenticatedToolsSalesEmailRoute: AuthenticatedToolsSalesEmailRoute,
  AuthenticatedToolsSocialPackRoute: AuthenticatedToolsSocialPackRoute,
  AuthenticatedProjectsIndexRoute: AuthenticatedProjectsIndexRoute,
  AuthenticatedToolsIndexRoute: AuthenticatedToolsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface ApiProjectsIdRouteChildren {
  ApiProjectsIdArchiveRoute: typeof ApiProjectsIdArchiveRoute
  ApiProjectsIdBriefRoute: typeof ApiProjectsIdBriefRoute
  ApiProjectsIdConfirmRoute: typeof ApiProjectsIdConfirmRoute
  ApiProjectsIdPauseRoute: typeof ApiProjectsIdPauseRoute
  ApiProjectsIdPlanRoute: typeof ApiProjectsIdPlanRoute
  ApiProjectsIdResumeRoute: typeof ApiProjectsIdResumeRoute
  ApiProjectsIdRunNextRoute: typeof ApiProjectsIdRunNextRoute
  ApiProjectsIdStepsStepIdRetryRoute: typeof ApiProjectsIdStepsStepIdRetryRoute
  ApiProjectsIdStepsStepIdRunRoute: typeof ApiProjectsIdStepsStepIdRunRoute
  ApiProjectsIdStepsStepIdSkipRoute: typeof ApiProjectsIdStepsStepIdSkipRoute
}

const ApiProjectsIdRouteChildren: ApiProjectsIdRouteChildren = {
  ApiProjectsIdArchiveRoute: ApiProjectsIdArchiveRoute,
  ApiProjectsIdBriefRoute: ApiProjectsIdBriefRoute,
  ApiProjectsIdConfirmRoute: ApiProjectsIdConfirmRoute,
  ApiProjectsIdPauseRoute: ApiProjectsIdPauseRoute,
  ApiProjectsIdPlanRoute: ApiProjectsIdPlanRoute,
  ApiProjectsIdResumeRoute: ApiProjectsIdResumeRoute,
  ApiProjectsIdRunNextRoute: ApiProjectsIdRunNextRoute,
  ApiProjectsIdStepsStepIdRetryRoute: ApiProjectsIdStepsStepIdRetryRoute,
  ApiProjectsIdStepsStepIdRunRoute: ApiProjectsIdStepsStepIdRunRoute,
  ApiProjectsIdStepsStepIdSkipRoute: ApiProjectsIdStepsStepIdSkipRoute,
}

const ApiProjectsIdRouteWithChildren = ApiProjectsIdRoute._addFileChildren(
  ApiProjectsIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  DemoRoute: DemoRoute,
  LegalRoute: LegalRoute,
  ApiCspReportRoute: ApiCspReportRoute,
  ApiDeleteAccountRoute: ApiDeleteAccountRoute,
  ApiGenerateAiRoute: ApiGenerateAiRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  PSlugRoute: PSlugRoute,
  RefCodeRoute: RefCodeRoute,
  ApiBillingCheckoutRoute: ApiBillingCheckoutRoute,
  ApiBillingPortalRoute: ApiBillingPortalRoute,
  ApiBillingWebhookRoute: ApiBillingWebhookRoute,
  ApiInternalReconcileCreditsRoute: ApiInternalReconcileCreditsRoute,
  ApiNotificationsWeeklySummaryQaRoute: ApiNotificationsWeeklySummaryQaRoute,
  ApiNotificationsWelcomeRoute: ApiNotificationsWelcomeRoute,
  ApiProjectsIdRoute: ApiProjectsIdRouteWithChildren,
  ApiProjectsCapabilitiesRoute: ApiProjectsCapabilitiesRoute,
  ApiWebhooksHotmartRoute: ApiWebhooksHotmartRoute,
  ApiProjectsIndexRoute: ApiProjectsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
